// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tperxqdnbzawtzqvqwkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZXJ4cWRuYnphd3R6cXZxd2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjAzNDYsImV4cCI6MjA2NjgzNjM0Nn0.ccbRWKowrmw8VPwLwrxdt4COHgu5_6H1HUU2xJNAvOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});